name: Resource Deployment (Push)

on: [push]

jobs:
  send-signal:
    name: Send CI/CD signal

    runs-on: ubuntu-latest

    steps:
      - name: Dispatch request
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_TOKEN_SITE_RESOURCE }}
          repository: RaenonX-DL/dragalia-site-resources
          event-type: data-updated
          client-payload: '{"message": "${{ github.repository }}@${{ github.sha }} - ${{ github.run_number }}"}'
